### PR TITLE
Create podspec file to allow package to be installed via CocoaPods on iOS

### PR DESCRIPTION
**Pull request by martin-nebel**

### CODE REVIEW

**Comment by luciapuccini** [comment]
Can you merge this? Thanks

**Comment by walterholohan** [comment]
Bump for merging. This will enable autolinking in the latest version of RN.

**Comment by taylor-made** [comment]
@jedi4ever please can you merge this?  The latest version of ReactNative made some changes to the way libraries are imported, and now the only way to do it is using a Podspec.  Thanks

**Comment by jedi4ever** [comment]
@taylor-made I can merge this , but can't test it ; this repo is currently unmaintained and this github organisation will stop soon. So if someone wants to step in as repo owner that would be awesome.

**Comment by walterholohan** [comment]
Hey @jedi4ever. I can take over ownership of this repo. After your last merge we still need to get the update published to NPM. So will also need to get ownership of the NPM repo for react-native-adobe-analytics so we can do this. My email is walter.holohan@gmail.com if you need to reach me.

**Pull request merged**
